// notices writes THIRD_PARTY_NOTICES.md: the license of every module
// linked into the gloss binary or the browser app, read from the module
// cache, so that what the binaries carry is what they credit.
//
//	go run ./internal/tools/notices > THIRD_PARTY_NOTICES.md
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type module struct {
	path, version, dir string
}

var licenseName = regexp.MustCompile(`(?i)^(LICENSE|LICENCE|COPYING|NOTICE)(\.(txt|md|rst))?$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run() error {
	modules := map[string]module{}
	// The native binary, and the browser app with its own module.
	for _, build := range []struct {
		dir  string
		env  []string
		pkgs string
	}{
		{".", nil, "./cmd/gloss"},
		{"examples/demo", []string{"GOOS=js", "GOARCH=wasm"}, "."},
	} {
		cmd := exec.Command("go", "list", "-deps", "-f", `{{with .Module}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}`, build.pkgs)
		cmd.Dir, cmd.Env = build.dir, append(os.Environ(), build.env...)
		out, err := cmd.Output()
		if err != nil {
			return fmt.Errorf("go list in %s: %w", build.dir, err)
		}
		for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
			fields := strings.Split(line, "\t")
			if len(fields) != 3 || fields[2] == "" || strings.HasPrefix(fields[0], "github.com/NimbleMarkets/gloss") {
				continue
			}
			if _, seen := modules[fields[0]]; !seen {
				modules[fields[0]] = module{fields[0], fields[1], fields[2]}
			}
		}
	}
	var paths []string
	for p := range modules {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString(`# Third-party notices

gloss is distributed under its own license, in LICENSE. The binaries, and
the browser app, link the modules below, whose licenses require that their
notices accompany what is built from them. Each notice is given as its module
carries it. This file is generated by internal/tools/notices from the modules
actually linked; it is shipped with every release and with the site.

The triangle rasterization in internal/document/export.go adapts the
NTCharts3d software renderer, whose license is among those below.

`)
	// The Go runtime and standard library are compiled into every binary.
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return err
	}
	if text, err := os.ReadFile(filepath.Join(strings.TrimSpace(string(goroot)), "LICENSE")); err == nil {
		section(&b, "The Go runtime and standard library", "https://go.dev", text)
	}
	section(&b, "PDFium", "compiled to WebAssembly by github.com/klippa-app/go-pdfium and embedded in the native binary; the browser app fetches @embedpdf/pdfium from jsDelivr instead", []byte(pdfiumLicense))
	// picky is carried in the tree rather than linked as a module.
	if text, err := os.ReadFile(filepath.Join("internal", "picky", "LICENSE")); err == nil {
		section(&b, "github.com/pgavlin/picky", "carried in internal/picky, with additions", text)
	} else {
		return fmt.Errorf("internal/picky/LICENSE: %w", err)
	}
	var missing []string
	for _, p := range paths {
		m := modules[p]
		entries, err := os.ReadDir(m.dir)
		if err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		var texts [][]byte
		for _, e := range entries {
			if !e.IsDir() && licenseName.MatchString(e.Name()) {
				text, err := os.ReadFile(filepath.Join(m.dir, e.Name()))
				if err != nil {
					return err
				}
				texts = append(texts, text)
			}
		}
		if len(texts) == 0 {
			missing = append(missing, p)
			continue
		}
		section(&b, m.path+" "+m.version, "", bytes.Join(texts, []byte("\n\n")))
	}
	if len(missing) > 0 {
		return fmt.Errorf("no license file in: %s", strings.Join(missing, ", "))
	}
	_, err = os.Stdout.Write(b.Bytes())
	return err
}

func section(b *bytes.Buffer, title, note string, text []byte) {
	fmt.Fprintf(b, "## %s\n\n", title)
	if note != "" {
		fmt.Fprintf(b, "%s\n\n", note)
	}
	b.WriteString("```\n")
	b.Write(bytes.TrimRight(text, "\n"))
	b.WriteString("\n```\n\n")
}

// PDFium's license, as its source carries it.
const pdfiumLicense = `Copyright 2014 The PDFium Authors

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
   * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`
